theme           = "harapeko2017"
baseURL         = "https://harapeko.netlify.com/"
title           = "はらぺこ屋"
enableGitInfo   = true
hasCJKLanguage	= true
DefaultContentLanguage = "ja"
Paginate = 12

pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "native"
pygmentsUseClasses = true

[params]
  googleanalytics = "UA-26792812-4"
  description = "猫と自転車と技術の日記"
  author      = "@harapeko_wktk"

[social]
  twitter = "harapeko_wktk"
  github = "harapeko"

[permalinks]
  food = "/:section/:title/"
  自転車 = "/:section/:title/"
  猫 = "/:section/:title/"
  技術 = "/:section/:title/"