theme           = "harapeko2017"
baseURL         = "https://harapeko.netlify.app"
title           = "はらぺこ屋"
enableGitInfo   = true
hasCJKLanguage	= true
DefaultContentLanguage = "ja"
Paginate = 12

pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "native"
pygmentsUseClasses = true

[params]
  googleanalytics = "UA-26792812-4"
  description = "猫と自転車と技術の日記"
  author      = "@harapeko_wktk"

[social]
  twitter = "harapeko_wktk"
  github = "harapeko"

[permalinks]
  food = "/:section/:title/"
  bike = "/:section/:title/"
  cat = "/:section/:title/"
  notes = "/:section/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
