theme           = "harapeko2017"
baseURL         = "https://machinist-switch-72660.netlify.com/"
title           = "はらぺこ屋"
googleanalytics = "UA-26792812-1"
enableGitInfo   = true
hasCJKLanguage	= true
DefaultContentLanguage = "ja"
Paginate = 11

[params]
  description = "猫と自転車と技術の日記"
  author      = "@harapeko_wktk"

[social]
  twitter = "harapeko_wktk"
  github = "harapeko"

[permalinks]
  food = "/:section/:title/"
  自転車 = "/:section/:title/"
  猫 = "/:section/:title/"
  技術 = "/:section/:title/"