title						= "はらぺこ屋"
languageCode		= "ja"
baseURL					= "http://harapeko.wktk.so/"
theme						= "harapeko2017"
hasCJKLanguage	= true

[params]
  description = "猫と自転車と技術の日記"
  googleanalytics = "UA-26792812-1"

[social]
  twitter = "harapeko_wktk"
  github = "harapeko"