theme           = "harapeko2017"
baseURL         = "https://machinist-switch-72660.netlify.com/"
title           = "はらぺこ屋"
googleanalytics = "UA-26792812-1"
enableGitInfo   = true
hasCJKLanguage	= true
DefaultContentLanguage = "ja"

[params]
  description = "猫と自転車と技術の日記"
  author      = "@harapeko_wktk"

[social]
  twitter = "harapeko_wktk"
  github = "harapeko"